
(function(){
 const $=(s,c=document)=>c.querySelector(s), $$=(s,c=document)=>Array.from(c.querySelectorAll(s));
 const btn=$('#gcMenuBtn'), side=$('#gcSidebar'), overlay=$('#gcOverlay');
 function close(){side&&side.classList.remove('open');overlay&&overlay.classList.remove('open')}
 if(btn&&side&&overlay){btn.addEventListener('click',()=>{side.classList.toggle('open');overlay.classList.toggle('open')});overlay.addEventListener('click',close);document.addEventListener('keydown',e=>{if(e.key==='Escape')close()})}
 const fixtures=window.GC_WC_FIXTURES||[];
 function now(){return new Date()}
 function fmt(d){try{return new Intl.DateTimeFormat('en-GB',{weekday:'short',day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit',timeZone:'Europe/London'}).format(new Date(d))}catch(e){return d}}
 function matchState(f){const start=new Date(f[0]); const t=now(); const end=new Date(start.getTime()+120*60000); if(t<start)return ['upcoming','Upcoming']; if(t>=start&&t<end)return ['live','LIVE']; return ['finished','Finished']}
 function renderFixtures(){const wrap=$('#fixturesList'); if(!wrap)return; const q=($('#fixtureSearch')?.value||'').toLowerCase(), g=$('#groupFilter')?.value||''; wrap.innerHTML=''; let list=fixtures.filter(f=>(!g||f[3]===g)&&(!q||f.join(' ').toLowerCase().includes(q))); if(!list.length){wrap.innerHTML='<div class="empty">No fixtures match this filter.</div>';return} for(const f of list){const st=matchState(f); const el=document.createElement('article'); el.className='fixture-card'; el.innerHTML=`<div><strong>${fmt(f[0])}</strong><br><small>${f[3]} · ${f[4]}</small></div><div class="fixture-teams">${f[1]} <span>vs</span> ${f[2]}<br><small>${f[5]||''}</small></div><div><span class="status ${st[0]}">${st[1]}</span> <button class="favourite" data-fav-type="match" data-fav-id="${f[1]} v ${f[2]}">☆</button></div>`; wrap.appendChild(el)} refreshFavButtons() }
 window.renderFixtures=renderFixtures; ['fixtureSearch','groupFilter'].forEach(id=>{const el=$('#'+id); if(el)el.addEventListener('input',renderFixtures)}); renderFixtures();
 function upcomingText(){let upcoming=fixtures.map(f=>({f,d:new Date(f[0])})).filter(x=>x.d>now()).sort((a,b)=>a.d-b.d)[0]; if(!upcoming)return '<div class="notice">No upcoming World Cup fixtures found in the local schedule file.</div>'; return `<div class="fixture-card"><div><strong>Next match</strong><br><small>${fmt(upcoming.f[0])}</small></div><div class="fixture-teams">${upcoming.f[1]} vs ${upcoming.f[2]}<br><small>${upcoming.f[3]} · ${upcoming.f[4]}</small></div><span class="status upcoming">Upcoming</span></div>`}
 const home=$('#homeFixtureStatus'); if(home)home.innerHTML=upcomingText(); const next=$('#nextMatchBox'); if(next)next.innerHTML=upcomingText();
 function countdown(){const el=$('#countdownBox'); if(!el)return; const start=new Date('2026-06-11T20:00:00+01:00'), t=now(); let diff=start-t; if(diff<=0){el.innerHTML='<div class="notice">World Cup 2026 has started. Follow fixtures for live and upcoming matches.</div>';return} const days=Math.floor(diff/864e5); diff-=days*864e5; const hrs=Math.floor(diff/36e5); diff-=hrs*36e5; const mins=Math.floor(diff/6e4); el.innerHTML=`<div class="stats-grid"><div class="stat"><strong>${days}</strong><span>Days</span></div><div class="stat"><strong>${hrs}</strong><span>Hours</span></div><div class="stat"><strong>${mins}</strong><span>Minutes</span></div><div class="stat"><strong>11 Jun</strong><span>Opening</span></div></div>`}
 countdown(); setInterval(countdown,60000);
 function favs(){try{return JSON.parse(localStorage.getItem('gcFavourites')||'{"team":[],"match":[],"group":[]}')}catch(e){return {team:[],match:[],group:[]}}}
 function saveFavs(f){localStorage.setItem('gcFavourites',JSON.stringify(f)); renderFavPage(); refreshFavButtons()}
 function refreshFavButtons(){const f=favs(); $$('[data-fav-type]').forEach(b=>{const type=b.dataset.favType,id=b.dataset.favId; const on=(f[type]||[]).includes(id); b.classList.toggle('active',on); b.textContent=on?'★':'☆'; b.onclick=()=>{const ff=favs(); ff[type]=ff[type]||[]; const i=ff[type].indexOf(id); if(i>=0)ff[type].splice(i,1); else ff[type].push(id); saveFavs(ff)}})}
 refreshFavButtons();
 function renderFavPage(){const wrap=$('#favContent'); if(!wrap)return; const active=$('.tab-btn.active')?.dataset.tab||'teams'; const f=favs(); if(active==='all'){let teams=Object.values(window.GC_WC_GROUPS||{}).flat(); wrap.innerHTML='<div class="teams-grid">'+teams.map(t=>`<div class="team-card"><h3>${t[1]} ${t[0]}</h3><button class="favourite" data-fav-type="team" data-fav-id="${t[0]}">☆</button></div>`).join('')+'</div>'; refreshFavButtons(); return}
 const key=active.replace('s',''); const arr=f[key]||[]; if(!arr.length){wrap.innerHTML='<div class="empty">No favourite '+active+' yet. Use the star buttons on teams, groups or fixtures.</div>'; return} wrap.innerHTML='<div class="news-list">'+arr.map(x=>`<div class="news-row"><span>FAVOURITE</span><strong>${x}</strong></div>`).join('')+'</div>' }
 $$('.tab-btn').forEach(b=>b.addEventListener('click',()=>{$$('.tab-btn').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderFavPage()})); renderFavPage();
})();
